version: 2.1
orbs:
  codecov: codecov/codecov@1.0.5
jobs:
  build:
    working_directory: ~/circleci-nzyme 
    docker:
      - image: circleci/openjdk:8-jdk
      - image: circleci/postgres:10.9-alpine-ram
    steps:
      - checkout
      - run: sudo apt-get update
      - run: sudo apt-get install postgresql-client
      - run: createdb nzyme-java-tests
      - restore_cache:
          key: nzyme-{{ checksum "pom.xml" }}
      - run: mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: nzyme-{{ checksum "pom.xml" }}
      - run: mvn package
      - codecov/upload:
          file: target/site/cobertura/coverage.xml
      - store_test_results:
          path: target/surefire-reports
