version: 2.1
orbs:
  codecov: codecov/codecov@1.0.5
jobs:
  build:
    working_directory: ~/circleci-nzyme 
    docker:
      - image: circleci/openjdk:8-jdk
        environment:
          - TEST_DATABASE_URL: postgresql://root@localhost/circle_test
      - image: circleci/postgres:10.9-alpine-ram
    steps:
      - checkout
      - run: sudo apt-get update
      - run: sudo apt-get install postgresql-client
      - run:
          name: install dockerize
          command: wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && sudo tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
          environment:
            DOCKERIZE_VERSION: v0.3.0
      - run:
          name: Wait for db
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - restore_cache:
          key: nzyme-{{ checksum "pom.xml" }}
      - run: mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: nzyme-{{ checksum "pom.xml" }}
      - run: mvn package
      - codecov/upload:
          file: target/site/cobertura/coverage.xml
      - store_test_results:
          path: target/surefire-reports
